import Link from "next/link";
import { crmPipelineTemplate, sampleCrmLeads } from "@keystone/crm";
import {
  AIPromptInput,
  BottomNav,
  Button,
  ConversationComposer,
  ConversationTimeline,
  ConversationTimelineItem,
  LeadCard,
  MessageBubble,
  SearchBar,
  SuggestionChips,
} from "@keystone/ui";

export default function HomePage() {
  const primaryLead = sampleCrmLeads[0];

  return (
    <main className="k-canvas-bg mx-auto flex min-h-dvh w-full max-w-5xl flex-col px-4 py-6 sm:px-6">
      <nav className="flex h-12 items-center justify-between">
        <Link className="font-display text-sm font-semibold text-ink-0" href="/">
          Keystone CRM
        </Link>
        <Button size="compact" variant="outline">
          Template
        </Button>
      </nav>

      <section className="grid flex-1 content-center gap-6 py-8">
        <div className="grid gap-5 lg:grid-cols-[1fr_360px] lg:items-end">
          <div>
            <p className="k-mono text-ink-4">CRM TEMPLATE</p>
            <h1 className="mt-3 max-w-2xl font-display text-[40px] font-medium leading-[1.02] tracking-normal text-ink-0 sm:text-5xl">
              Leads, conversations, follow-ups, reminders, and matching.
            </h1>
            <p className="mt-4 max-w-xl text-[15px] leading-7 text-ink-3">
              This template composes the Keystone conversation engine, AI SDK, workflow engine, and
              design system without duplicating platform logic.
            </p>
          </div>
          <AIPromptInput
            suggestions={[
              "Draft follow-up for Sophia",
              "Find top property matches",
              "Create reminders from inbox",
            ]}
          />
        </div>

        <div className="grid gap-4 lg:grid-cols-[1fr_360px]">
          <div className="grid gap-3">
            <SearchBar />
            <LeadCard
              aiAction={primaryLead.aiAction}
              budget={primaryLead.budget}
              name={primaryLead.name}
              status={primaryLead.stage}
            />
            <div className="grid grid-cols-5 gap-2 overflow-x-auto pb-1">
              {crmPipelineTemplate.map((stage) => (
                <div
                  className="min-w-28 rounded-3 border border-line bg-white p-3"
                  key={stage.name}
                >
                  <div className="k-mono">{stage.kind}</div>
                  <div className="mt-2 text-sm font-medium text-ink-1">{stage.name}</div>
                </div>
              ))}
            </div>
          </div>
          <SuggestionChips
            chips={[
              { ai: true, text: "AI follow-up required · today" },
              { ai: true, text: "3 properties match Sophia" },
              { ai: false, text: "Reminder · call Theo at 16:00" },
              { ai: true, text: "Lead detected from WhatsApp" },
            ]}
          />
        </div>

        <section className="grid gap-4 lg:grid-cols-[1fr_360px]">
          <div className="rounded-5 border border-line bg-white shadow-1">
            <ConversationTimeline>
              <ConversationTimelineItem isFirst meta="12m" title="Sophia" tone="message">
                <MessageBubble>Can we move Saturday&apos;s viewing to noon?</MessageBubble>
              </ConversationTimelineItem>
              <ConversationTimelineItem
                action="Generated by Keystone AI SDK"
                meta="now"
                title="AI follow-up"
                tone="ai"
              >
                Confirm noon, attach the Marais shortlist, and set a reminder for Friday.
              </ConversationTimelineItem>
              <ConversationTimelineItem isLast meta="today" title="Reminder" tone="task">
                Call before sending the property match pack.
              </ConversationTimelineItem>
            </ConversationTimeline>
            <div className="p-3 pt-0">
              <ConversationComposer />
            </div>
          </div>

          <div className="grid content-start gap-3">
            {sampleCrmLeads.map((lead) => (
              <div className="rounded-4 border border-line bg-white p-4 shadow-1" key={lead.name}>
                <div className="flex items-center justify-between">
                  <span className="text-sm font-medium text-ink-1">{lead.name}</span>
                  <span className="k-mono">{lead.score}</span>
                </div>
                <div className="mt-2 text-xs text-ink-4">{lead.budget}</div>
                <div className="mt-3 rounded-2 bg-ai-surface px-3 py-2 text-xs font-medium text-ink-1">
                  {lead.aiAction}
                </div>
              </div>
            ))}
          </div>
        </section>
      </section>

      <div className="sticky bottom-0 -mx-4 sm:hidden">
        <BottomNav active="leads" />
      </div>
    </main>
  );
}
